import os
import time
import logging
from typing import Dict, Any, List, Optional
from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.outputs import ChatResult, ChatGeneration
from ..config import settings

logger = logging.getLogger(__name__)

# Check if we should use Mock LLM
def is_mock_mode() -> bool:
    return (
        not settings.GOOGLE_API_KEY 
        or settings.GOOGLE_API_KEY == "mock-key-if-not-set" 
        or settings.GOOGLE_API_KEY.strip() == ""
    )

class MockChatOpenAI(BaseChatModel):
    """
    A Mock LLM that returns pre-defined response structures to avoid crashing
    when no OpenAI API key is supplied.
    """
    model_name: str = "mock-model"

    def _generate(
        self,
        messages: List[BaseMessage],
        stop: Optional[List[str]] = None,
        run_manager: Optional[Any] = None,
        **kwargs: Any,
    ) -> Any:
        # Check if the prompt is for evaluation (LLM-as-a-Judge) or generation (PRD)
        system_content = ""
        user_content = ""
        
        for msg in messages:
            if isinstance(msg, SystemMessage):
                system_content = msg.content
            elif isinstance(msg, HumanMessage):
                user_content = msg.content

        # Simple logic to determine if it is an evaluation or PRD generation
        if "evaluate" in system_content.lower() or "score" in system_content.lower() or "judge" in system_content.lower():
            # Return JSON evaluation
            import json
            response_json = {
                "coverage": 85.0,
                "hallucination": 90.0,
                "design": 80.0,
                "engineering": 75.0,
                "qa": 70.0,
                "prototype": 80.0,
                "repetition": 95.0,
                "format": 90.0,
                "reasoning": "The mock judge rates this document as high quality with minimal errors."
            }
            time.sleep(0.5) # Simulate latency
            generation = ChatGeneration(message=AIMessage(content=json.dumps(response_json)))
            return ChatResult(generations=[generation])
        else:
            # PRD generation
            prd_output = f"""# Product Requirement Document: Generated by Mock LLM

## 1. Executive Summary
This is a mock generated PRD for the problem: "{user_content[:100]}...".

## 2. Product Goals
- Goal 1: Build a scalable solution.
- Goal 2: Ensure fast response times.

## 3. Scope & Requirements
- Requirement 1: User authentication and security.
- Requirement 2: Clean and intuitive interface layout.

## 4. Engineering Architecture
- Tech Stack: React, FastAPI, PostgreSQL.
- API Endpoints: GET /api/v1/resource, POST /api/v1/resource.

## 5. QA Scenarios
- Scenario 1: Successful login flow verification.
- Scenario 2: Error handling when data input is empty.
"""
            time.sleep(1.0) # Simulate latency
            generation = ChatGeneration(message=AIMessage(content=prd_output))
            return ChatResult(generations=[generation])

    @property
    def _llm_type(self) -> str:
        return "mock-chat-openai"

def get_llm(
    model_name: Optional[str] = None,
    max_tokens: Optional[int] = None,
    temperature: Optional[float] = None,
    response_mime_type: Optional[str] = None,
) -> BaseChatModel:
    """
    Factory to return either standard LangChain ChatGoogleGenerativeAI or MockChatOpenAI based on API key availability.
    """
    if is_mock_mode():
        logger.info("Initializing in MOCK LLM mode (no API key configured).")
        return MockChatOpenAI()
    
    selected_model = model_name or settings.GEMINI_MODEL
    logger.info(f"Initializing ChatGoogleGenerativeAI model: {selected_model}")
    from langchain_google_genai import ChatGoogleGenerativeAI
    return ChatGoogleGenerativeAI(
        model=selected_model,
        google_api_key=settings.GOOGLE_API_KEY,
        temperature=0.2 if temperature is None else temperature,
        max_tokens=max_tokens or settings.GEMINI_MAX_TOKENS,
        request_timeout=45,
        retries=1,
        response_mime_type=response_mime_type
    )
